server:
  port: 80
spring:
  application:
    name: cloud-consume-order
  #consul 注册中心地址
  cloud:
    consul:
      host: localhost
      discovery:
        port: 8500
        service-name: ${spring.application.name}
        prefer-ip-address: true
